
package com.cesanta.cloud;

// GENERATED FILE DO NOT EDIT
// This file is automatically generated with clubbygen.

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

import com.cesanta.clubby.lib.Clubby;
import com.cesanta.clubby.lib.CmdListener;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Services service provides support for introspection.
 */
public final class ServicesService {

    private final Clubby clubby;

    public static ServicesService createInstance(Clubby clubby) {
        return new ServicesService(clubby);
    }

    private ServicesService(Clubby clubby) {
        this.clubby = clubby;
    }


    //-- Get {{{

    /**
     * Get returns definitions of all services provided by the server.
     */
    public void get(
            ServicesService.GetArgs args,
            CmdListener<ServicesService.GetResponse> listener
            ) {
        clubby.callBackend(
                "/v1/Services.Get",
                args,
                listener,
                ServicesService.GetResponse.class
                );
    }

    //-- args {{{

    /**
     * Arguments for the {@link com.cesanta.cloud.ServicesService#get get} method.
     */
    public static final class GetArgs  {


    }


    // }}}

    //-- response {{{

    /**
     * Response of the {@link com.cesanta.cloud.ServicesService#get get} method.
     */
    public static final class GetResponse extends HashMap<String, Object> {

        static final long serialVersionUID = 1;


    }


    // }}}

    // }}}


}

