
package com.cesanta.cloud;

// GENERATED FILE DO NOT EDIT
// This file is automatically generated with clubbygen.

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

import com.cesanta.clubby.lib.Clubby;
import com.cesanta.clubby.lib.ClubbyOptions;
import com.cesanta.clubby.lib.CmdListener;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Auth service performs authentication and authorization of devices and commands. Can only be used by the cloud backend.
 */
public final class AuthService {

    private final Clubby clubby;
    private ClubbyOptions defaultOpts;

    public static AuthService createInstance(Clubby clubby) {
        return new AuthService(clubby);
    }

    private AuthService(Clubby clubby) {
        this.clubby = clubby;
        this.defaultOpts = clubby.getOptions();
    }


    //-- Authenticate {{{

    /**
     * Authenticate returns true if `id` is verified to have valid credentials.
     *
     * @param opts
     *      Options instance which will override current default options. If
     *      there is a need to override defaults, use {@link
     *      AuthService#getOptions() getOptions()} to get current defaults, and then
     *      modify received options object in some way.
     */
    public void authenticate(
            AuthService.AuthenticateArgs args,
            CmdListener<Boolean> listener,
            ClubbyOptions opts
            ) {
        clubby.callBackend(
                "/v1/Auth.Authenticate",
                args,
                listener,
                Boolean.class,
                opts
                );
    }

    /**
     * Authenticate returns true if `id` is verified to have valid credentials.
     */
    public void authenticate(
            AuthService.AuthenticateArgs args,
            CmdListener<Boolean> listener
            ) {
        authenticate(args, listener, defaultOpts);
    }

    //-- args {{{

    /**
     * Arguments for the {@link com.cesanta.cloud.AuthService#authenticate authenticate} method.
     */
    public static final class AuthenticateArgs  {

        /**
         * Credentials presented by the entity. At least one of `psk` or `cert` must be present.
         */
        @JsonProperty("credentials")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private AuthenticateArgsCredential credentials = new AuthenticateArgsCredential();

        /**
         * ID of an entity to authenticate.
         */
        @JsonProperty("id")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String id;


        /**
         * Set credentials presented by the entity. At least one of `psk` or `cert` must be present.
         */
        public AuthenticateArgs credentials(AuthenticateArgsCredential credentials) {
            this.credentials = credentials;
            return this;
        }

        /**
         * Set ID of an entity to authenticate.
         */
        public AuthenticateArgs id(String id) {
            this.id = id;
            return this;
        }

    }


    public static final class AuthenticateArgsCredential  {

        @JsonProperty("cert")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String cert;

        @JsonProperty("psk")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String psk;


        /**
         * Set cert
         */
        public AuthenticateArgsCredential cert(String cert) {
            this.cert = cert;
            return this;
        }

        /**
         * Set psk
         */
        public AuthenticateArgsCredential psk(String psk) {
            this.psk = psk;
            return this;
        }

    }


    // }}}

    //-- response {{{

    // }}}

    // }}}

    //-- AuthorizeCommand {{{

    /**
     * AuthorizeCommand returns true if `src` is allowed to send a given command to `dst`.
     *
     * @param opts
     *      Options instance which will override current default options. If
     *      there is a need to override defaults, use {@link
     *      AuthService#getOptions() getOptions()} to get current defaults, and then
     *      modify received options object in some way.
     */
    public void authorizeCommand(
            AuthService.AuthorizeCommandArgs args,
            CmdListener<Boolean> listener,
            ClubbyOptions opts
            ) {
        clubby.callBackend(
                "/v1/Auth.AuthorizeCommand",
                args,
                listener,
                Boolean.class,
                opts
                );
    }

    /**
     * AuthorizeCommand returns true if `src` is allowed to send a given command to `dst`.
     */
    public void authorizeCommand(
            AuthService.AuthorizeCommandArgs args,
            CmdListener<Boolean> listener
            ) {
        authorizeCommand(args, listener, defaultOpts);
    }

    //-- args {{{

    /**
     * Arguments for the {@link com.cesanta.cloud.AuthService#authorizeCommand authorizeCommand} method.
     */
    public static final class AuthorizeCommandArgs  {

        /**
         * Command name.
         */
        @JsonProperty("cmd")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String cmd;

        /**
         * ID of the command recipient.
         */
        @JsonProperty("dst")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String dst;

        /**
         * ID of the command sender.
         */
        @JsonProperty("src")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String src;


        /**
         * Set command name.
         */
        public AuthorizeCommandArgs cmd(String cmd) {
            this.cmd = cmd;
            return this;
        }

        /**
         * Set ID of the command recipient.
         */
        public AuthorizeCommandArgs dst(String dst) {
            this.dst = dst;
            return this;
        }

        /**
         * Set ID of the command sender.
         */
        public AuthorizeCommandArgs src(String src) {
            this.src = src;
            return this;
        }

    }


    // }}}

    //-- response {{{

    // }}}

    // }}}


    public void setDefaultOptions(ClubbyOptions opts) {
        this.defaultOpts = ClubbyOptions.createFrom(opts);
    }

    public ClubbyOptions getOptions() {
        return ClubbyOptions.createFrom(defaultOpts);
    }
}

