// This is a generated file. Not intended for manual editing.
//
// GENERATED FILE DO NOT EDIT
// This file is automatically generated with clubbygen.
//
//
// Copyright (c) 2016 Cesanta Software Limited
// All rights reserved
//

package com.cesanta.cloud;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

import com.cesanta.clubby.lib.Clubby;
import com.cesanta.clubby.lib.ClubbyOptions;
import com.cesanta.clubby.lib.CmdListener;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Provides methods to manage devices.
 */
public final class DeviceService {

    private final Clubby clubby;
    private ClubbyOptions defaultOpts;

    public static DeviceService createInstance(Clubby clubby) {
        return new DeviceService(clubby);
    }

    private DeviceService(Clubby clubby) {
        this.clubby = clubby;
        this.defaultOpts = clubby.getOptions();
    }


    //-- Add {{{

    /**
     * Adds a new device.
     *
     * @param opts
     *      Options instance which will override current default options. If
     *      there is a need to override defaults, use {@link
     *      DeviceService#getOptions() getOptions()} to get current defaults, and then
     *      modify received options object in some way.
     */
    public void add(
            DeviceService.AddArgs args,
            CmdListener<DeviceService.AddResponse> listener,
            ClubbyOptions opts
            ) {
        clubby.callBackend(
                "/v1/Device.Add",
                args,
                listener,
                DeviceService.AddResponse.class,
                opts
                );
    }

    /**
     * Adds a new device.
     */
    public void add(
            DeviceService.AddArgs args,
            CmdListener<DeviceService.AddResponse> listener
            ) {
        add(args, listener, defaultOpts);
    }

    //-- args {{{

    /**
     * Arguments for the {@link com.cesanta.cloud.DeviceService#add add} method.
     */
    public static final class AddArgs  {

        /**
         * ID of the device.
         */
        @JsonProperty("deviceid")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String deviceid;

        /**
         * If set to `true`, then it won't be an error to call this method for
an already existing (and owned by the same user) device; instead, 
it will just update device psk.

         */
        @JsonProperty("force")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private Boolean force;

        /**
         * Optional name of the account to add device to.
         */
        @JsonProperty("owner")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String owner;

        /**
         * Pre-shared key that device will use for authentication.
         */
        @JsonProperty("psk")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String psk;


        /**
         * Set ID of the device.
         */
        public AddArgs deviceid(String deviceid) {
            this.deviceid = deviceid;
            return this;
        }

        /**
         * Set if set to `true`, then it won't be an error to call this method for
an already existing (and owned by the same user) device; instead, 
it will just update device psk.

         */
        public AddArgs force(boolean force) {
            this.force = force;
            return this;
        }

        /**
         * Set optional name of the account to add device to.
         */
        public AddArgs owner(String owner) {
            this.owner = owner;
            return this;
        }

        /**
         * Set pre-shared key that device will use for authentication.
         */
        public AddArgs psk(String psk) {
            this.psk = psk;
            return this;
        }

    }


    // }}}

    //-- response {{{

    /**
     * Response of the {@link com.cesanta.cloud.DeviceService#add add} method.
     */
    public static final class AddResponse  {


    }


    // }}}

    // }}}

    //-- Claim {{{

    /**
     * Claim an unclaimed device using a token.
     *
     * @param opts
     *      Options instance which will override current default options. If
     *      there is a need to override defaults, use {@link
     *      DeviceService#getOptions() getOptions()} to get current defaults, and then
     *      modify received options object in some way.
     */
    public void claim(
            DeviceService.ClaimArgs args,
            CmdListener<DeviceService.ClaimResponse> listener,
            ClubbyOptions opts
            ) {
        clubby.callBackend(
                "/v1/Device.Claim",
                args,
                listener,
                DeviceService.ClaimResponse.class,
                opts
                );
    }

    /**
     * Claim an unclaimed device using a token.
     */
    public void claim(
            DeviceService.ClaimArgs args,
            CmdListener<DeviceService.ClaimResponse> listener
            ) {
        claim(args, listener, defaultOpts);
    }

    //-- args {{{

    /**
     * Arguments for the {@link com.cesanta.cloud.DeviceService#claim claim} method.
     */
    public static final class ClaimArgs  {

        /**
         * ID of the device.
         */
        @JsonProperty("deviceid")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String deviceid;

        /**
         * Name of the account that will own the device. Defaults to the identity of the caller
         */
        @JsonProperty("owner")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String owner;

        /**
         * Auth token based on PSK.
         */
        @JsonProperty("token")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String token;


        /**
         * Set ID of the device.
         */
        public ClaimArgs deviceid(String deviceid) {
            this.deviceid = deviceid;
            return this;
        }

        /**
         * Set name of the account that will own the device. Defaults to the identity of the caller
         */
        public ClaimArgs owner(String owner) {
            this.owner = owner;
            return this;
        }

        /**
         * Set auth token based on PSK.
         */
        public ClaimArgs token(String token) {
            this.token = token;
            return this;
        }

    }


    // }}}

    //-- response {{{

    /**
     * Response of the {@link com.cesanta.cloud.DeviceService#claim claim} method.
     */
    public static final class ClaimResponse  {


    }


    // }}}

    // }}}

    //-- Delete {{{

    /**
     * Unregisters the device
     *
     * @param opts
     *      Options instance which will override current default options. If
     *      there is a need to override defaults, use {@link
     *      DeviceService#getOptions() getOptions()} to get current defaults, and then
     *      modify received options object in some way.
     */
    public void delete(
            DeviceService.DeleteArgs args,
            CmdListener<DeviceService.DeleteResponse> listener,
            ClubbyOptions opts
            ) {
        clubby.callBackend(
                "/v1/Device.Delete",
                args,
                listener,
                DeviceService.DeleteResponse.class,
                opts
                );
    }

    /**
     * Unregisters the device
     */
    public void delete(
            DeviceService.DeleteArgs args,
            CmdListener<DeviceService.DeleteResponse> listener
            ) {
        delete(args, listener, defaultOpts);
    }

    //-- args {{{

    /**
     * Arguments for the {@link com.cesanta.cloud.DeviceService#delete delete} method.
     */
    public static final class DeleteArgs  {

        /**
         * ID of the device.
         */
        @JsonProperty("deviceid")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String deviceid;


        /**
         * Set ID of the device.
         */
        public DeleteArgs deviceid(String deviceid) {
            this.deviceid = deviceid;
            return this;
        }

    }


    // }}}

    //-- response {{{

    /**
     * Response of the {@link com.cesanta.cloud.DeviceService#delete delete} method.
     */
    public static final class DeleteResponse  {


    }


    // }}}

    // }}}

    //-- GetInfo {{{

    /**
     * Gets device information.
     *
     * @param opts
     *      Options instance which will override current default options. If
     *      there is a need to override defaults, use {@link
     *      DeviceService#getOptions() getOptions()} to get current defaults, and then
     *      modify received options object in some way.
     */
    public void getInfo(
            DeviceService.GetInfoArgs args,
            CmdListener<DeviceService.GetInfoResponse> listener,
            ClubbyOptions opts
            ) {
        clubby.callBackend(
                "/v1/Device.GetInfo",
                args,
                listener,
                DeviceService.GetInfoResponse.class,
                opts
                );
    }

    /**
     * Gets device information.
     */
    public void getInfo(
            DeviceService.GetInfoArgs args,
            CmdListener<DeviceService.GetInfoResponse> listener
            ) {
        getInfo(args, listener, defaultOpts);
    }

    //-- args {{{

    /**
     * Arguments for the {@link com.cesanta.cloud.DeviceService#getInfo getInfo} method.
     */
    public static final class GetInfoArgs  {

        /**
         * ID of the device.
         */
        @JsonProperty("deviceid")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String deviceid;


        /**
         * Set ID of the device.
         */
        public GetInfoArgs deviceid(String deviceid) {
            this.deviceid = deviceid;
            return this;
        }

    }


    // }}}

    //-- response {{{

    public static final class GetInfoResponse  {

        /**
         * ID of the device.
         */
        @JsonProperty("deviceid")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        public String deviceid;

        /**
         * Optional name of the account owning the device
         */
        @JsonProperty("owner")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        public String owner;

        /**
         * Pre-shared key that device will use for authentication.
         */
        @JsonProperty("psk")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        public String psk;


    }


    // }}}

    // }}}

    //-- List {{{

    /**
     * Returns the list of owned devices
     *
     * @param opts
     *      Options instance which will override current default options. If
     *      there is a need to override defaults, use {@link
     *      DeviceService#getOptions() getOptions()} to get current defaults, and then
     *      modify received options object in some way.
     */
    public void list(
            DeviceService.ListArgs args,
            CmdListener<DeviceService.ListResponse> listener,
            ClubbyOptions opts
            ) {
        clubby.callBackend(
                "/v1/Device.List",
                args,
                listener,
                DeviceService.ListResponse.class,
                opts
                );
    }

    /**
     * Returns the list of owned devices
     */
    public void list(
            DeviceService.ListArgs args,
            CmdListener<DeviceService.ListResponse> listener
            ) {
        list(args, listener, defaultOpts);
    }

    //-- args {{{

    /**
     * Arguments for the {@link com.cesanta.cloud.DeviceService#list list} method.
     */
    public static final class ListArgs  {

        /**
         * name of account
         */
        @JsonProperty("account")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String account;

        /**
         * An object with labels to query for. Object keys are label names, corresponding values are label values.
         */
        @JsonProperty("labels")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private Map<String, String> labels = new HashMap<String, String>();


        /**
         * Set name of account
         */
        public ListArgs account(String account) {
            this.account = account;
            return this;
        }

        /**
         * Add an item to the an object with labels to query for. Object keys are label names, corresponding values are label values.
         */
        public ListArgs label(String key, String label) {
            this.labels.put(key, label);
            return this;
        }

    }


    // }}}

    //-- response {{{

    /**
     * Response of the {@link com.cesanta.cloud.DeviceService#list list} method.
     */
    public static final class ListResponse extends ArrayList<String> {

        static final long serialVersionUID = 1;


    }


    // }}}

    // }}}


    public void setDefaultOptions(ClubbyOptions opts) {
        this.defaultOpts = ClubbyOptions.createFrom(opts);
    }

    public ClubbyOptions getOptions() {
        return ClubbyOptions.createFrom(defaultOpts);
    }
}

