
package com.cesanta.cloud;

// GENERATED FILE DO NOT EDIT
// This file is automatically generated with clubbygen.

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

import com.cesanta.clubby.lib.Clubby;
import com.cesanta.clubby.lib.CmdListener;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Misc APIs provided by the HTTP frontend.
 */
public final class FrontendService {

    private final Clubby clubby;

    public static FrontendService createInstance(Clubby clubby) {
        return new FrontendService(clubby);
    }

    private FrontendService(Clubby clubby) {
        this.clubby = clubby;
    }


    //-- BlobURL {{{

    /**
     * Returns an HTTP URL which points to the given blobstore key.
     */
    public void blobURL(
            FrontendService.BlobURLArgs args,
            CmdListener<String> listener
            ) {
        clubby.callBackend(
                "/v1/Frontend.BlobURL",
                args,
                listener,
                String.class
                );
    }

    //-- args {{{

    /**
     * Arguments for the {@link com.cesanta.cloud.FrontendService#blobURL blobURL} method.
     */
    public static final class BlobURLArgs  {

        /**
         * Blobstore key.
         */
        @JsonProperty("key")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private List<String> key = new ArrayList<String>();


        /**
         * Add an item to the blobstore key.
         */
        public BlobURLArgs key(String key) {
            this.key.add(key);
            return this;
        }

    }


    // }}}

    //-- response {{{

    // }}}

    // }}}


}

