/*
 * GENERATED FILE DO NOT EDIT
 * This file is automatically generated with clubbygen.
 *
 * Copyright (c) 2016 Cesanta Software Limited
 * All rights reserved
 */

package com.cesanta.cloud;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

import com.cesanta.clubby.lib.Clubby;
import com.cesanta.clubby.lib.ClubbyOptions;
import com.cesanta.clubby.lib.CmdListener;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Misc APIs provided by the HTTP frontend.
 */
public final class FrontendService {

    private final Clubby clubby;
    private ClubbyOptions defaultOpts;

    public static FrontendService createInstance(Clubby clubby) {
        return new FrontendService(clubby);
    }

    private FrontendService(Clubby clubby) {
        this.clubby = clubby;
        this.defaultOpts = clubby.getOptions();
    }


    //-- BlobURL {{{

    /**
     * Returns an HTTP URL which points to the given blobstore key.
     *
     * @param opts
     *      Options instance which will override current default options. If
     *      there is a need to override defaults, use {@link
     *      FrontendService#getOptions() getOptions()} to get current defaults, and then
     *      modify received options object in some way.
     */
    public void blobURL(
            FrontendService.BlobURLArgs args,
            CmdListener<String> listener,
            ClubbyOptions opts
            ) {
        clubby.callBackend(
                "/v1/Frontend.BlobURL",
                args,
                listener,
                String.class,
                opts
                );
    }

    /**
     * Returns an HTTP URL which points to the given blobstore key.
     */
    public void blobURL(
            FrontendService.BlobURLArgs args,
            CmdListener<String> listener
            ) {
        blobURL(args, listener, defaultOpts);
    }

    //-- args {{{

    /**
     * Arguments for the {@link com.cesanta.cloud.FrontendService#blobURL blobURL} method.
     */
    public static final class BlobURLArgs  {

        /**
         * Blobstore key.
         */
        @JsonProperty("key")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private List<String> key = new ArrayList<String>();


        /**
         * Add an item to the blobstore key.
         */
        public BlobURLArgs key(String key) {
            this.key.add(key);
            return this;
        }

    }


    // }}}

    //-- response {{{

    // }}}

    // }}}


    public void setDefaultOptions(ClubbyOptions opts) {
        this.defaultOpts = ClubbyOptions.createFrom(opts);
    }

    public ClubbyOptions getOptions() {
        return ClubbyOptions.createFrom(defaultOpts);
    }
}

