// This is a generated file. Not intended for manual editing.
//
// GENERATED FILE DO NOT EDIT
// This file is automatically generated with clubbygen.
//
//
// Copyright (c) 2016 Cesanta Software Limited
// All rights reserved
//

package com.cesanta.cloud;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

import com.cesanta.clubby.lib.Clubby;
import com.cesanta.clubby.lib.ClubbyOptions;
import com.cesanta.clubby.lib.CmdListener;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Moncruise service allows dynamically size a group of VMs. Groups and rules are defined in a configuration file. Methods in this service allows callers to manually size the groups and obtain stats from the mgos tool without having to open the status page.
 */
public final class MoncruiseService {

    private final Clubby clubby;
    private ClubbyOptions defaultOpts;

    public static MoncruiseService createInstance(Clubby clubby) {
        return new MoncruiseService(clubby);
    }

    private MoncruiseService(Clubby clubby) {
        this.clubby = clubby;
        this.defaultOpts = clubby.getOptions();
    }


    //-- ListGroups {{{

    /**
     * List configured VM groups.

     *
     * @param opts
     *      Options instance which will override current default options. If
     *      there is a need to override defaults, use {@link
     *      MoncruiseService#getOptions() getOptions()} to get current defaults, and then
     *      modify received options object in some way.
     */
    public void listGroups(
            MoncruiseService.ListGroupsArgs args,
            CmdListener<MoncruiseService.ListGroupsResponse> listener,
            ClubbyOptions opts
            ) {
        clubby.callBackend(
                "/v1/Moncruise.ListGroups",
                args,
                listener,
                MoncruiseService.ListGroupsResponse.class,
                opts
                );
    }

    /**
     * List configured VM groups.

     */
    public void listGroups(
            MoncruiseService.ListGroupsArgs args,
            CmdListener<MoncruiseService.ListGroupsResponse> listener
            ) {
        listGroups(args, listener, defaultOpts);
    }

    //-- args {{{

    /**
     * Arguments for the {@link com.cesanta.cloud.MoncruiseService#listGroups listGroups} method.
     */
    public static final class ListGroupsArgs  {


    }


    // }}}

    //-- response {{{

    /**
     * Response of the {@link com.cesanta.cloud.MoncruiseService#listGroups listGroups} method.
     */
    public static final class ListGroupsResponse extends ArrayList<ListGroupsResponseItem> {

        static final long serialVersionUID = 1;


    }


    public static final class ListGroupsResponseItem  {

        @JsonProperty("currentSize")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        public Long currentSize;

        @JsonProperty("maxSize")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        public Long maxSize;

        @JsonProperty("members")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        public List<ListGroupsResponseItemMember> members;

        @JsonProperty("minSize")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        public Long minSize;

        @JsonProperty("name")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        public String name;


    }


    public static final class ListGroupsResponseItemMember  {

        @JsonProperty("name")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        public String name;

        @JsonProperty("up")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        public Boolean up;


    }


    // }}}

    // }}}

    //-- Resize {{{

    /**
     * Resize a group of VMs.

     *
     * @param opts
     *      Options instance which will override current default options. If
     *      there is a need to override defaults, use {@link
     *      MoncruiseService#getOptions() getOptions()} to get current defaults, and then
     *      modify received options object in some way.
     */
    public void resize(
            MoncruiseService.ResizeArgs args,
            CmdListener<MoncruiseService.ResizeResponse> listener,
            ClubbyOptions opts
            ) {
        clubby.callBackend(
                "/v1/Moncruise.Resize",
                args,
                listener,
                MoncruiseService.ResizeResponse.class,
                opts
                );
    }

    /**
     * Resize a group of VMs.

     */
    public void resize(
            MoncruiseService.ResizeArgs args,
            CmdListener<MoncruiseService.ResizeResponse> listener
            ) {
        resize(args, listener, defaultOpts);
    }

    //-- args {{{

    /**
     * Arguments for the {@link com.cesanta.cloud.MoncruiseService#resize resize} method.
     */
    public static final class ResizeArgs  {

        /**
         * Name of a VM group.
         */
        @JsonProperty("group")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private String group;

        @JsonProperty("size")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        private Long size;


        /**
         * Set name of a VM group.
         */
        public ResizeArgs group(String group) {
            this.group = group;
            return this;
        }

        /**
         * Set size
         */
        public ResizeArgs size(long size) {
            this.size = size;
            return this;
        }

    }


    // }}}

    //-- response {{{

    public static final class ResizeResponse  {


    }


    // }}}

    // }}}


    public void setDefaultOptions(ClubbyOptions opts) {
        this.defaultOpts = ClubbyOptions.createFrom(opts);
    }

    public ClubbyOptions getOptions() {
        return ClubbyOptions.createFrom(defaultOpts);
    }
}

